name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Restore keystore.jks
      run: echo "${{secrets.RELEASE_STORE_FILE}}" | base64 -d > /tmp/keystore.jks

    - name: Restore gradle.properties
      run: |
        mkdir -p ~/.gradle/
        echo "RELEASE_STORE_FILE=/tmp/keystore.jks" >> ~/.gradle/gradle.properties
        echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> ~/.gradle/gradle.properties
        echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> ~/.gradle/gradle.properties
        echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> ~/.gradle/gradle.properties
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build

